### ISSUE TITLE
Update is_admin in Admin cog to pull from config.json

### ISSUE THREAD

**Issue by jonah-dev** [jonah-dev/lfd2-bot#3]
Make sure to update the example.config.json as well

**Comment by jonah-dev** [comment]
@JoeDailey Come Monday let's discuss how we'd like to tackle configs

**Comment by celowsky** [comment]
Is this issue still relevant? The `example.config.json` file no longer exists in the repo. A KMS seems like it would provide a better solution here.

**Comment by celowsky** [comment]
Related: https://github.com/jonah-dev/lfd2-bot/issues/43#issue-782647109

**Comment by JoeDailey** [comment]
#47
