### ISSUE TITLE
Display Lobby on Each Join or Leave

### ISSUE THREAD

**Issue by jonah-dev** [jonah-dev/lfd2-bot#6]
Take the logic from ?lobby, move it into a separate function like `displayLobby` and call it after successful join and leaves.

**Comment by jonah-dev** [comment]
@JoeDailey Trying to think of a good way to tackle this without spamming the channel. One of the ideas that I had was maybe going back and deleting the previous lobby message and posting a new one every time a new user joins? What do you think about this?

**Comment by JoeDailey** [comment]
This was completed in #39
